# Generated by Django 4.2 on 2023-04-10 20:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="url",
        ),
    ]
