# Generated by Django 4.2 on 2023-04-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_alter_menuitem_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункты меню",
            },
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="position",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="url",
        ),
        migrations.AddField(
            model_name="menu",
            name="slug",
            field=models.SlugField(
                max_length=255, null=True, verbose_name="Ссылка"
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="slug",
            field=models.SlugField(
                max_length=255, null=True, verbose_name="Ссылка"
            ),
        ),
    ]
