# Generated by Django 4.2 on 2023-04-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "menu",
            "0004_alter_menuitem_options_remove_menuitem_position_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="slug",
            field=models.SlugField(max_length=255, verbose_name="Ссылка"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="slug",
            field=models.SlugField(max_length=255, verbose_name="Ссылка"),
        ),
    ]
