# Generated by Django 4.2 on 2023-04-12 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0005_alter_menu_slug_alter_menuitem_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="slug",
        ),
    ]
